# Generated by Django 6.0.5 on 2026-05-13 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apppermission_role_userdirectpermission_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='codename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='apppermission',
            unique_together={('codename', 'organization')},
        ),
    ]
